# Generated by Django 2.0.5 on 2018-05-10 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('text', models.TextField(verbose_name='Açıklama')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturulma Tarihi')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Yayınlanma Tarihi')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
